env:
  browser: true
  es2021: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project:
    - "./tsconfig.json"
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - airbnb
  - airbnb/hooks
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
plugins:
  - "@typescript-eslint"
  - react
  - react-hooks
  - jsx-a11y
  - import
  - unused-imports
rules:
  # basics
  prefer-const: error
  no-unused-vars: off # 未使用の変数のチェックは @typescript-eslint/no-unused-vars に任せているのでこちらはoff
  prefer-arrow-callback: error
  func-style:
    - error
    - expression
  no-void:
    - error
    - allowAsStatement: true
  padding-line-between-statements:
    - error
    - blankLine: always
      prev: "*"
      next: return

  # jsx-a11y
  jsx-a11y/no-autofocus: off
  jsx-a11y/anchor-is-valid:
    - error
    - components:
        - Link
      specialLink:
        - hrefLeft
        - hrefRight
      aspects:
        - invalidHref
        - preferButton

  # import
  import/extensions: off
  import/no-duplicates: error
  unused-imports/no-unused-imports: error
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - object
        - index
        - type
      pathGroups:
        - pattern: "{react,react-dom/**,react-router-dom}"
          group: builtin
          position: before
      newlines-between: always
      pathGroupsExcludedImportTypes:
        - builtin
      alphabetize:
        order: asc
        caseInsensitive: true

  # @typescript-eslint
  "@typescript-eslint/no-use-before-define": error
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/no-unused-vars":
    - error
    - vars: all
      args: after-used
      ignoreRestSiblings: false
      argsIgnorePattern: "_"
      varsIgnorePattern: "_"
  "@typescript-eslint/naming-convention":
    - error
    - selector:
        - typeAlias
        - typeParameter
      format:
        - PascalCase
    - selector:
        - property
        - method
      format:
        - camelCase

  # React
  react/prop-types: off
  react/react-in-jsx-scope: off
  react/jsx-one-expression-per-line: off
  react/destructuring-assignment: error
  react/jsx-filename-extension:
    - error
    - extensions:
        - ".jsx"
        - ".tsx"
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
  react/jsx-props-no-spreading:
    - error
    - html: enforce
      custom: enforce
      explicitSpread: ignore

# 除外対象
ignorePatterns:
  - "build/"
  - "dist/"
  - "public/"
  - "**/node_modules/"
  - "*.config.js"
  - "*.config.ts"
